FROM ubuntu:latest
RUN apt-get -qq update; apt-get -qqy install mercurial
RUN hg clone https://hg.prosody.im/prosody-modules/ /usr/lib/prosody/extra-modules/

FROM prosody/prosody:0.11
USER root
COPY --from=0 /usr/lib/prosody/extra-modules/ /usr/lib/prosody/extra-modules/
RUN apt-get -qq update; apt-get -qqy install luarocks
RUN apt-get -qqy install make liblua5.2-dev lua5.2 liblua5.2

RUN cd /tmp; wget -O - http://luarocks.org/releases/luarocks-3.3.1.tar.gz | tar xvz; cd luarocks-3.3.1; ./configure --lua-version=5.2 --versioned-rocks-dir; make build; make install

RUN apt-get -qqy install libsasl2-dev libldap2-dev libssl-dev
RUN cd /tmp; wget -O - https://github.com/lualdap/lualdap/archive/v1.2.5.tar.gz | tar xvz; cd lualdap-1.2.5; /usr/local/bin/luarocks make

RUN /usr/local/bin/luarocks install luasocket
RUN /usr/local/bin/luarocks install luasec

RUN apt-get -qqy install libevent-dev
RUN /usr/local/bin/luarocks install luaevent

RUN apt-get -qqy install libmariadb-dev libmariadb-dev-compat
RUN /usr/local/bin/luarocks install luadbi-mysql MYSQL_INCDIR=/usr/include/mariadb/

ENV EXTRA_MODULES "bookmarks blocking smacks csi csi_battery_saver track_muc_joins presence_cache cloud_notify auth_ldap http_upload omemo_all_access pep_vcard_avatar migrate muc_mam vcard_muc turncredentials alias conversejs"
RUN for MOD in ${EXTRA_MODULES}; do ln -s /usr/lib/prosody/extra-modules/mod_${MOD} /usr/lib/prosody/modules/; done

# add to external group: ssl-cert (115)
RUN groupadd -g 115 ssl-cert-ex; usermod -a -G ssl-cert-ex prosody
